### ISSUE TITLE
Опечатка в туториале

### ISSUE THREAD

**Issue by zzzzzzzzzzzzz** [neuro-ml/dicom-csv#1]
<img width="1080" alt="Снимок экрана 2020-03-03 в 15 22 21" src="https://user-images.githubusercontent.com/4963723/75776998-2c547000-5d66-11ea-8231-8f96bbb7a62e.png">

**Comment by maxme1** [comment]
What typo do you mean? `dicom_csv` does have the `join_tree` function

**Comment by maxme1** [comment]
Fixed. Thanks.
