### ISSUE TITLE
Исчезновение ImageOrientationPatient0/1/2/3/4/5

### ISSUE THREAD

**Issue by zzzzzzzzzzzzz** [neuro-ml/dicom-csv#3]
Воспроизведение:
![Снимок экрана 2020-04-09 в 17 51 24](https://user-images.githubusercontent.com/4963723/78909439-3156be80-7a8c-11ea-90f8-6a310d4759a4.png)
Загрузим данные определенного пациента из iplan
![Снимок экрана 2020-04-09 в 17 50 39](https://user-images.githubusercontent.com/4963723/78909431-2e5bce00-7a8c-11ea-9196-3ca2ade7b3b7.png)
При попытке для строки после aggregate_images вызвать функцию get_fixed_orientation_matrix, замечаем, что не хватает полей ImageOrientationPatient0/1/2/3/4/5. Посмотрим на датафрейм, и их действительно там нет.

Посмотрим на метаданные
![Снимок экрана 2020-04-09 в 17 52 39](https://user-images.githubusercontent.com/4963723/78909442-33208200-7a8c-11ea-86c5-e93c29643067.png)
Слева снимок для которого эта ошибка воспроизводится (из iplan-а), справа снимок для которого этот код отрабатывает без ошибок (из eclipse-а)

у снимка из iplan-а более нетривиальная ориентация

**Comment by kurmukovai** [comment]
Это происходит в aggregate_images, изза того что дропаются все неуникальные колонки. ImageOrientationPatient должны быть уникальны внутри одного SeriesInstanceUID но в случае слева, они могут отличаться в 7-8 знаке изза ошибок округления.

`    def get_unique_cols(df):
        return [col for col in df.columns if len(df[col].dropna().unique()) == 1]

    def process_group(entry):
        if process_series is not None:
            entry = process_series(entry)

        res = entry.iloc[[0]][get_unique_cols(entry)]`

**Comment by kurmukovai** [comment]
Вообще это должно было пофикситься еще в join_tree, там при считывании ImageOrientationPatient есть округление до 5ого знака после запятой.

**Comment by zzzzzzzzzzzzz** [comment]
Нужно считывать именно папку с КТ. Столбец ImageOrientation в примере выше подсовывается из МРТ

**Comment by kurmukovai** [comment]
Ок, на скриншоте видно что ImageOrientationPatient не является уникальным, мне не понятно, это все еще какие то ошибки округления/хранения float'ов или дело в том что во время КТ он реально менялся.

Возможное решение - сделать более аггресивное округление в join_tree. Или сохранять ImageOrientationPatient0-5 подобно тому как мы сохраняем другие неуникальные поля в aggregate_images.
@maxme1 есть какие мысли?

![Screenshot from 2020-04-09 20-03-25](https://user-images.githubusercontent.com/14237010/78921186-37a16680-7a9d-11ea-824d-e664f11500b4.png)

**Comment by zzzzzzzzzzzzz** [comment]
На скриншоте видно, что значения для разных дайкомов в пределах серии действительно отличаются
![Снимок экрана 2020-04-09 в 20 09 52](https://user-images.githubusercontent.com/4963723/78921851-36bd0480-7a9e-11ea-8051-d82bfd3589bf.png)

**Comment by zzzzzzzzzzzzz** [comment]
Причем если повнимательнее посмотреть, то там есть отличия и в 3-ем знаке после запятой

**Comment by maxme1** [comment]
Думаю лучше с этим бороться в `aggregate_images` туда можно подать `process_series`, который округлит как ему нравится.
btw, let's switch to english.

**Comment by zzzzzzzzzzzzz** [comment]
Finally, I decided to use this process_series function and just set ImageOrientation0/1/2/3/4/5 to its' mean values
`def process_series(series):
    to_mean_cols = ['ImageOrientationPatient0', 'ImageOrientationPatient1',
       'ImageOrientationPatient2', 'ImageOrientationPatient3',
       'ImageOrientationPatient4', 'ImageOrientationPatient5',]
    mean_vals = series[to_mean_cols].mean()
    for col in to_mean_cols:
        series[col] = mean_vals[col]
    
    return series.sort_values('FileName')`
